// 25 varied synthetic crisis scenarios used to seed the deployed CrisisProof
// contract end-to-end (case -> evidence -> response options -> review).
// Organisation names and incidents are fictional; evidence URLs point at
// real, generally-fetchable public pages so the contract's live web-fetch
// (gl.nondet.web.render) has real content to corroborate against.

export const scenarios = [
  {
    title: "Customer database exposed via misconfigured backup",
    organisation: "Northwind Retail",
    crisis_type: "DATA_BREACH",
    incident_summary: "A cloud storage bucket holding nightly customer database backups was left publicly readable for approximately 40 hours before discovery.",
    affected_users: "Roughly 2.1 million registered customers",
    reported_harm: "Exposure of names, emails, hashed passwords, and partial payment tokens",
    urgency_level: "CRITICAL",
    decision_deadline: "Within 2 hours",
    current_response_hypothesis: "Revoke public access immediately and force a password reset for all accounts",
    known_constraints: "Cannot take checkout offline during peak sales weekend",
    evidence_summary: "Security scanner alert plus access logs showing anonymous reads from multiple IP ranges",
    evidence: [{
      title: "Access log excerpt showing anonymous bucket reads",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Data_breach",
      evidence_hash: "9f2a1c7e4b3d0f6a",
      source_name: "Internal SIEM",
      source_credibility_note: "Automated, cross-referenced with cloud provider audit trail",
      relevance: "Confirms unauthorized external access window and IP ranges involved",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Force password reset and disclose within 2 hours", summary: "Immediately revoke bucket access, force resets, and publish a disclosure notice.", action_type: "CONTAINMENT_AND_DISCLOSURE", expected_benefit: "Limits credential reuse damage and meets regulatory disclosure windows", key_risk: "Reset flow may overload support channels", affected_stakeholders: "All registered customers, support team, legal", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Public status page notice plus direct email", failure_conditions: "Reset emails delayed beyond 4 hours" },
      { title: "Quiet containment pending forensics", summary: "Revoke access silently and wait for forensic confirmation before any disclosure.", action_type: "CONTAINMENT_ONLY", expected_benefit: "Avoids premature or inaccurate public statements", key_risk: "Delayed disclosure may violate breach notification laws", affected_stakeholders: "Legal, executive team", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only until forensics complete", failure_conditions: "Regulator or press learns of the breach before disclosure" },
    ],
  },
  {
    title: "Core checkout service down across all regions",
    organisation: "Lumen Commerce",
    crisis_type: "SERVICE_OUTAGE",
    incident_summary: "A bad configuration push to the payments gateway caused a 100% failure rate on checkout for six hours.",
    affected_users: "All active shoppers globally, an estimated 400,000 sessions",
    reported_harm: "Failed transactions, abandoned carts, and duplicate charges reported by some customers",
    urgency_level: "HIGH",
    decision_deadline: "Within 1 hour",
    current_response_hypothesis: "Roll back the configuration push to the last known-good version",
    known_constraints: "Rollback tooling has not been exercised in production before",
    evidence_summary: "Monitoring dashboards and customer support ticket volume spike",
    evidence: [{
      title: "Error rate dashboard snapshot",
      evidence_type: "METRIC",
      evidence_url: "https://en.wikipedia.org/wiki/Downtime",
      evidence_hash: "3b7d8e21ac590fd4",
      source_name: "Monitoring system",
      source_credibility_note: "Automated, high confidence",
      relevance: "Shows checkout error rate rising from 0.2% to 100% at deploy time",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Roll back the configuration deploy", summary: "Revert the payments gateway config to the last known-good release.", action_type: "MITIGATION", expected_benefit: "Restores checkout immediately", key_risk: "Rollback tooling is unproven and could fail partway", affected_stakeholders: "All customers, on-call engineering", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Status page update", failure_conditions: "Rollback fails to restore service within 30 minutes" },
      { title: "Hotfix the gateway config in place", summary: "Patch the specific faulty parameter without a full rollback.", action_type: "MITIGATION", expected_benefit: "Avoids reverting unrelated recent changes", key_risk: "Slower to validate, may miss a related root cause", affected_stakeholders: "All customers, on-call engineering", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Status page update", failure_conditions: "Hotfix introduces a new regression" },
    ],
  },
  {
    title: "Guest reports serious injury at theme attraction",
    organisation: "Cascade Family Parks",
    crisis_type: "SAFETY_INCIDENT",
    incident_summary: "A guest sustained a fractured wrist after a restraint mechanism failed on a ride during normal operation.",
    affected_users: "The injured guest and approximately 24 other riders on the same cycle",
    reported_harm: "Physical injury requiring hospital treatment",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Shut down the ride and all rides sharing the same restraint model pending inspection",
    known_constraints: "Ride closure during a holiday weekend will materially affect park revenue",
    evidence_summary: "Maintenance logs, guest statement, and on-site medical report",
    evidence: [{
      title: "On-site medical incident report",
      evidence_type: "INCIDENT_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Amusement_park",
      evidence_hash: "77c1e4a92f0b83d6",
      source_name: "Park medical staff",
      source_credibility_note: "First-hand, documented at time of incident",
      relevance: "Confirms nature and severity of injury and ride identifier",
      category: "OPERATIONAL",
    }],
    response_options: [
      { title: "Shut down affected ride class fleet-wide", summary: "Close the ride and all others sharing the same restraint hardware until inspected.", action_type: "SAFETY_SHUTDOWN", expected_benefit: "Prevents further injury from the same failure mode", key_risk: "Significant revenue and guest satisfaction impact", affected_stakeholders: "All guests, ride operations staff", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "On-site signage and guest services briefing", failure_conditions: "Inspection cannot be completed before next operating day" },
      { title: "Close only the specific unit involved", summary: "Shut down the single ride unit while other units of the same model keep running.", action_type: "PARTIAL_SHUTDOWN", expected_benefit: "Limits revenue impact while removing the immediate hazard", key_risk: "Does not address a possible fleet-wide defect", affected_stakeholders: "Guests riding the affected unit, safety team", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "On-site signage only", failure_conditions: "A similar failure occurs on another unit of the same model" },
    ],
  },
  {
    title: "Executive email leaked with disparaging customer remarks",
    organisation: "Halcyon Airlines",
    crisis_type: "PR_CRISIS",
    incident_summary: "An internal email from a senior executive mocking customers affected by a recent delay was leaked to a journalist.",
    affected_users: "General public and brand reputation",
    reported_harm: "Reputational damage and social media backlash",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 12 hours",
    current_response_hypothesis: "Issue a public apology and clarify the email does not reflect company policy",
    known_constraints: "Executive in question is still employed and legal has not cleared a statement",
    evidence_summary: "Screenshot of the leaked email circulating on social media, verified against internal mail server logs",
    evidence: [{
      title: "Leaked email screenshot with verification",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Public_relations",
      evidence_hash: "1a4f6c8d3e29b0f5",
      source_name: "Communications team",
      source_credibility_note: "Verified against internal mail server headers",
      relevance: "Confirms authenticity and original recipient list of the email",
      category: "COMMUNICATIONS",
    }],
    response_options: [
      { title: "Public apology and policy clarification", summary: "Issue a statement apologizing and clarifying this does not reflect company values.", action_type: "PUBLIC_STATEMENT", expected_benefit: "Limits reputational damage and shows accountability", key_risk: "May be seen as insufficient without personnel action", affected_stakeholders: "Customers, press, employees", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Press statement and social media post", failure_conditions: "Statement is perceived as insincere and backlash intensifies" },
      { title: "Internal review before any public comment", summary: "Conduct an internal HR review before making any public statement.", action_type: "INVESTIGATE_FIRST", expected_benefit: "Ensures the eventual response is accurate and legally sound", key_risk: "Silence during the review window may worsen public perception", affected_stakeholders: "Executive team, HR, legal", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None until review concludes", failure_conditions: "Story escalates nationally before review concludes" },
    ],
  },
  {
    title: "Coordinated account takeover ring drains user wallets",
    organisation: "Fenwick Pay",
    crisis_type: "FRAUD",
    incident_summary: "A credential-stuffing campaign compromised roughly 1,800 accounts and drained stored balances via automated transfers.",
    affected_users: "1,800 confirmed compromised accounts",
    reported_harm: "Direct financial loss to affected users",
    urgency_level: "CRITICAL",
    decision_deadline: "Within 1 hour",
    current_response_hypothesis: "Freeze outbound transfers platform-wide and force re-authentication for all users",
    known_constraints: "Freezing transfers will also block legitimate transactions in progress",
    evidence_summary: "Fraud detection alerts and transaction pattern analysis showing rapid sequential transfers",
    evidence: [{
      title: "Transaction pattern anomaly report",
      evidence_type: "FRAUD_ALERT",
      evidence_url: "https://en.wikipedia.org/wiki/Credential_stuffing",
      evidence_hash: "5c9e2b7a1f4d0836",
      source_name: "Fraud detection system",
      source_credibility_note: "Automated, corroborated by transfer logs",
      relevance: "Shows a common IP/device fingerprint pattern across compromised accounts",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Platform-wide transfer freeze", summary: "Immediately halt all outbound transfers and require re-authentication.", action_type: "CONTAINMENT", expected_benefit: "Stops further fund loss across all accounts", key_risk: "Blocks legitimate in-flight transactions and angers unaffected users", affected_stakeholders: "All account holders", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "In-app banner and push notification", failure_conditions: "Freeze fails to stop transfers already queued" },
      { title: "Targeted freeze on flagged accounts only", summary: "Freeze only the accounts matching the compromise fingerprint.", action_type: "TARGETED_CONTAINMENT", expected_benefit: "Limits disruption to unaffected users", key_risk: "May miss accounts not yet flagged by the detection model", affected_stakeholders: "Flagged account holders", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Direct notification to flagged users", failure_conditions: "New compromised accounts appear outside the flagged set" },
    ],
  },
  {
    title: "Ransomware encrypts internal file servers",
    organisation: "Briarwood Health Network",
    crisis_type: "SECURITY_INCIDENT",
    incident_summary: "A ransomware strain encrypted several internal file servers including scheduling systems, discovered by IT at 3am.",
    affected_users: "Internal staff across 6 clinic locations; indirectly, patients with scheduled appointments",
    reported_harm: "Operational disruption to appointment scheduling and records access",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Isolate affected servers from the network and switch to paper-based scheduling temporarily",
    known_constraints: "Cannot confirm yet whether patient records were exfiltrated before encryption",
    evidence_summary: "IT incident log and ransom note screenshot",
    evidence: [{
      title: "Ransom note and encrypted file listing",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Ransomware",
      evidence_hash: "6d1f8a3c9e5b207f",
      source_name: "IT security team",
      source_credibility_note: "First-hand, captured at time of discovery",
      relevance: "Confirms scope of encrypted systems and ransom demand",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Isolate and rebuild from backups", summary: "Disconnect affected servers, do not pay ransom, restore from the last clean backup.", action_type: "CONTAINMENT_AND_RECOVERY", expected_benefit: "Avoids funding attackers and restores clean systems", key_risk: "Backup may be days old, causing data loss", affected_stakeholders: "Clinic staff, patients", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal staff briefing, patient notice only if records affected", failure_conditions: "Backups are also found to be compromised" },
      { title: "Engage incident response firm before any action", summary: "Bring in an external IR firm to assess exfiltration risk before touching systems.", action_type: "INVESTIGATE_FIRST", expected_benefit: "Preserves forensic evidence and clarifies exfiltration scope", key_risk: "Extends downtime for clinics", affected_stakeholders: "Clinic staff, patients, legal", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only during investigation", failure_conditions: "IR firm cannot be engaged within the operational window" },
    ],
  },
  {
    title: "Regulator flags undisclosed data-sharing practice",
    organisation: "Verdant Insurance Group",
    crisis_type: "REGULATORY_CRISIS",
    incident_summary: "A state regulator issued a formal inquiry into whether customer health data was shared with a marketing partner without proper disclosure.",
    affected_users: "Policyholders whose data may have been shared, estimated 90,000",
    reported_harm: "Potential privacy violation and regulatory penalty exposure",
    urgency_level: "HIGH",
    decision_deadline: "Within 5 business days",
    current_response_hypothesis: "Suspend the data-sharing arrangement and prepare a compliance response to the regulator",
    known_constraints: "Marketing partner contract has a 30-day termination notice clause",
    evidence_summary: "Copy of the regulator's inquiry letter and the data-sharing agreement",
    evidence: [{
      title: "Regulator inquiry letter",
      evidence_type: "LEGAL_DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Data_Protection_Directive",
      evidence_hash: "2e7b9c4f1a8d0356",
      source_name: "Legal department",
      source_credibility_note: "Official correspondence, verified authentic",
      relevance: "Specifies the exact disclosure requirement alleged to be unmet",
      category: "LEGAL",
    }],
    response_options: [
      { title: "Suspend data sharing and self-report", summary: "Pause the partner arrangement immediately and proactively respond to the regulator.", action_type: "COMPLIANCE_ACTION", expected_benefit: "Demonstrates good faith and may reduce penalty severity", key_risk: "Contractual penalty for early suspension", affected_stakeholders: "Policyholders, marketing partner, legal", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Formal regulator response, no public statement yet", failure_conditions: "Suspension breaches contract terms without a force majeure clause" },
      { title: "Continue sharing pending legal review", summary: "Maintain the current arrangement while legal reviews the disclosure requirements.", action_type: "MAINTAIN_STATUS_QUO", expected_benefit: "Avoids contractual penalties during review", key_risk: "Regulator may view continued sharing as an aggravating factor", affected_stakeholders: "Policyholders, legal", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None externally", failure_conditions: "Regulator escalates to a formal enforcement action during review" },
    ],
  },
  {
    title: "Key contract manufacturer halts production without notice",
    organisation: "Solstice Electronics",
    crisis_type: "SUPPLY_CHAIN",
    incident_summary: "The sole contract manufacturer for a flagship product line halted production citing a labor dispute, with no confirmed restart date.",
    affected_users: "Retail partners and pre-order customers",
    reported_harm: "Inventory shortfall and potential delivery delays",
    urgency_level: "HIGH",
    decision_deadline: "Within 3 days",
    current_response_hypothesis: "Activate a backup manufacturer while negotiating a resolution with the primary one",
    known_constraints: "Backup manufacturer has 6-week ramp-up time and higher unit cost",
    evidence_summary: "Manufacturer notice letter and current inventory levels across warehouses",
    evidence: [{
      title: "Production halt notice from manufacturer",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Supply_chain",
      evidence_hash: "8a3d5f9c2e1b7046",
      source_name: "Procurement team",
      source_credibility_note: "Official notice from the manufacturer's account team",
      relevance: "Confirms halt reason and lack of a committed restart date",
      category: "OPERATIONAL",
    }],
    response_options: [
      { title: "Activate backup manufacturer immediately", summary: "Begin ramp-up at the secondary contract manufacturer in parallel with negotiations.", action_type: "DIVERSIFY_SUPPLY", expected_benefit: "Reduces dependency risk and preserves some delivery timeline", key_risk: "Higher unit cost erodes margin on affected orders", affected_stakeholders: "Retail partners, customers, finance", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Partner notice with revised timelines", failure_conditions: "Backup manufacturer also cannot meet the ramp-up timeline" },
      { title: "Wait for primary manufacturer resolution", summary: "Hold current orders and continue negotiating with the primary manufacturer only.", action_type: "MAINTAIN_STATUS_QUO", expected_benefit: "Avoids the cost premium of a backup supplier", key_risk: "Extended shortfall if the labor dispute is prolonged", affected_stakeholders: "Retail partners, customers", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Internal only for now", failure_conditions: "Dispute extends beyond 4 weeks with no resolution in sight" },
    ],
  },
  {
    title: "Warehouse worker seriously injured by forklift",
    organisation: "Ridgeline Logistics",
    crisis_type: "WORKPLACE_INCIDENT",
    incident_summary: "A warehouse associate suffered a leg injury after being struck by a forklift operating in a pedestrian aisle.",
    affected_users: "The injured associate and warehouse floor staff",
    reported_harm: "Physical injury and potential OSHA reportable event",
    urgency_level: "HIGH",
    decision_deadline: "Within 4 hours",
    current_response_hypothesis: "Suspend forklift operations in the affected zone and review pedestrian barrier compliance",
    known_constraints: "Suspending the zone will delay same-day shipping commitments",
    evidence_summary: "Incident report from shift supervisor and warehouse camera footage log",
    evidence: [{
      title: "Shift supervisor incident report",
      evidence_type: "INCIDENT_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Occupational_safety_and_health",
      evidence_hash: "4f8b2d6a9c1e0357",
      source_name: "Warehouse operations",
      source_credibility_note: "First-hand account, corroborated by camera footage",
      relevance: "Confirms sequence of events and whether pedestrian barriers were in place",
      category: "OPERATIONAL",
    }],
    response_options: [
      { title: "Suspend forklift traffic in the affected zone", summary: "Halt forklift operations in the zone pending a safety audit.", action_type: "SAFETY_SHUTDOWN", expected_benefit: "Prevents further injury while the root cause is assessed", key_risk: "Delays same-day shipping for orders staged in that zone", affected_stakeholders: "Warehouse staff, shipping customers", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal safety briefing", failure_conditions: "Audit cannot be completed within the shift" },
      { title: "Add temporary pedestrian barriers and continue operations", summary: "Install additional barriers immediately without a full operational pause.", action_type: "PARTIAL_MITIGATION", expected_benefit: "Reduces risk while maintaining shipping commitments", key_risk: "Does not address whether the barrier gap was the root cause", affected_stakeholders: "Warehouse staff", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal safety briefing", failure_conditions: "A second near-miss occurs in the same zone" },
    ],
  },
  {
    title: "Contamination detected in packaged salad product line",
    organisation: "Greenfield Foods",
    crisis_type: "PRODUCT_RECALL",
    incident_summary: "Routine testing found listeria contamination in a batch of packaged salad already distributed to retail stores in three states.",
    affected_users: "Consumers who purchased the affected batch codes",
    reported_harm: "Risk of foodborne illness, no confirmed cases yet",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Issue an immediate voluntary recall of the affected batch codes",
    known_constraints: "Full traceability to individual retail shipments is not yet complete",
    evidence_summary: "Lab test results and batch distribution manifest",
    evidence: [{
      title: "Third-party lab contamination test results",
      evidence_type: "LAB_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Food_safety",
      evidence_hash: "0c6e9a3f7b2d1584",
      source_name: "Independent food safety lab",
      source_credibility_note: "Accredited third-party lab, results confirmed on retest",
      relevance: "Confirms contamination type and affected batch codes",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Immediate voluntary recall of affected batches", summary: "Issue a public recall notice for the specific batch codes and notify retailers.", action_type: "RECALL", expected_benefit: "Removes contaminated product from shelves quickly, limits illness risk", key_risk: "Incomplete traceability may miss some affected shipments", affected_stakeholders: "Consumers, retailers, regulators", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Public recall notice and retailer alert", failure_conditions: "Traceability gaps leave contaminated product on shelves" },
      { title: "Broader precautionary recall of the full product line", summary: "Recall the entire salad product line, not just the confirmed batch codes.", action_type: "RECALL", expected_benefit: "Eliminates risk from any traceability gaps", key_risk: "Significant unnecessary cost and waste if contamination is isolated", affected_stakeholders: "Consumers, retailers, farmers supplying unaffected batches", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Public recall notice", failure_conditions: "Recall scope still misses an affected distribution channel" },
    ],
  },
  {
    title: "Payment processor outage blocks subscription renewals",
    organisation: "Orbital Streaming",
    crisis_type: "PAYMENT_FAILURE",
    incident_summary: "The third-party payment processor experienced an outage causing all subscription renewal charges to fail for 18 hours.",
    affected_users: "Subscribers with renewal dates during the outage window, roughly 300,000",
    reported_harm: "Service interruption for customers whose renewal failed and access was suspended",
    urgency_level: "HIGH",
    decision_deadline: "Within 3 hours",
    current_response_hypothesis: "Temporarily suspend automatic access revocation for failed renewals until the processor recovers",
    known_constraints: "Cannot directly control the third-party processor's recovery timeline",
    evidence_summary: "Processor status page and internal billing failure logs",
    evidence: [{
      title: "Payment processor status page snapshot",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Payment_processor",
      evidence_hash: "d4a7c2e9f1b83056",
      source_name: "Billing system",
      source_credibility_note: "Automated, cross-referenced with processor's public status page",
      relevance: "Confirms outage window and correlates with renewal failure spike",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Suspend access revocation during the outage", summary: "Grant a grace period so customers keep access despite failed renewal charges.", action_type: "CUSTOMER_PROTECTION", expected_benefit: "Prevents customer-facing disruption for a vendor-caused failure", key_risk: "Revenue recognition delay and potential for retry failures later", affected_stakeholders: "Affected subscribers, finance", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "In-app notice to affected users", failure_conditions: "Processor outage extends beyond 48 hours" },
      { title: "Switch to backup payment processor", summary: "Fail over renewal charges to a secondary payment processor for the duration of the outage.", action_type: "FAILOVER", expected_benefit: "Restores normal renewal processing without a grace period", key_risk: "Backup processor may have different fraud rules causing false declines", affected_stakeholders: "Affected subscribers, finance, fraud team", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "None if transparent to customers", failure_conditions: "Backup processor rejects a significant share of valid charges" },
    ],
  },
  {
    title: "Location tracking data shared with advertiser beyond consent scope",
    organisation: "Pathway Maps",
    crisis_type: "PRIVACY_VIOLATION",
    incident_summary: "An internal audit found that precise location data was shared with an advertising partner beyond what users consented to in the privacy policy.",
    affected_users: "Users who opted into approximate location sharing only, estimated 500,000",
    reported_harm: "Privacy violation and potential loss of user trust",
    urgency_level: "HIGH",
    decision_deadline: "Within 24 hours",
    current_response_hypothesis: "Immediately cut off the excess data fields being shared and notify affected users",
    known_constraints: "Advertising partner relationship generates significant revenue",
    evidence_summary: "Internal audit findings comparing consent scope to actual data fields transmitted",
    evidence: [{
      title: "Internal privacy audit report",
      evidence_type: "AUDIT_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Information_privacy",
      evidence_hash: "e1b5c8a3f6d02947",
      source_name: "Internal privacy team",
      source_credibility_note: "First-hand audit with data field comparison logs",
      relevance: "Confirms which specific data fields exceeded consent scope",
      category: "COMPLIANCE",
    }],
    response_options: [
      { title: "Cut off excess data sharing and notify users", summary: "Immediately restrict shared fields to the consented scope and send a user notice.", action_type: "COMPLIANCE_ACTION", expected_benefit: "Stops ongoing violation and demonstrates transparency", key_risk: "Advertising partner revenue impact and possible contract dispute", affected_stakeholders: "Affected users, advertising partner, legal", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Direct user notification and privacy policy update", failure_conditions: "Technical fix cannot be deployed within the notification window" },
      { title: "Restrict data sharing without user notification yet", summary: "Fix the technical issue immediately but delay user notice pending legal review.", action_type: "PARTIAL_COMPLIANCE", expected_benefit: "Stops the violation immediately while legal assesses notification obligations", key_risk: "Delayed notice may be seen as concealment if discovered independently", affected_stakeholders: "Affected users, legal", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "None until legal review completes", failure_conditions: "Issue is independently discovered before notice goes out" },
    ],
  },
  {
    title: "Coordinated bot network floods platform with spam listings",
    organisation: "Marketplace Nine",
    crisis_type: "PLATFORM_ABUSE",
    incident_summary: "A bot network created over 50,000 fraudulent listings in 12 hours, degrading search quality and enabling scam transactions.",
    affected_users: "All active buyers and sellers on the platform",
    reported_harm: "Degraded trust, some users reporting scam purchases from fraudulent listings",
    urgency_level: "HIGH",
    decision_deadline: "Within 6 hours",
    current_response_hypothesis: "Mass-suspend accounts matching the bot signature and add CAPTCHA to listing creation",
    known_constraints: "Some legitimate power sellers may share behavioral traits with the bot signature",
    evidence_summary: "Trust and safety detection report showing account creation velocity and listing patterns",
    evidence: [{
      title: "Bot signature detection report",
      evidence_type: "FRAUD_ALERT",
      evidence_url: "https://en.wikipedia.org/wiki/Internet_bot",
      evidence_hash: "b9d3f6a1e8c02745",
      source_name: "Trust and safety team",
      source_credibility_note: "Automated detection, manually spot-checked on a sample",
      relevance: "Confirms the shared behavioral signature used to identify bot accounts",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Mass-suspend flagged accounts and add CAPTCHA", summary: "Suspend all accounts matching the bot signature and require CAPTCHA on new listings.", action_type: "CONTAINMENT", expected_benefit: "Rapidly removes fraudulent listings and slows new bot creation", key_risk: "Risk of suspending legitimate power sellers with similar patterns", affected_stakeholders: "Buyers, sellers, flagged account holders", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Appeal process notice for suspended sellers", failure_conditions: "False positive rate among suspended legitimate sellers exceeds 5%" },
      { title: "Shadow-restrict flagged listings without suspending accounts", summary: "Hide flagged listings from search without suspending the underlying accounts.", action_type: "SOFT_CONTAINMENT", expected_benefit: "Reduces buyer exposure while avoiding false-positive suspensions", key_risk: "Bot network may adapt and continue creating new listings", affected_stakeholders: "Buyers, sellers", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None externally", failure_conditions: "Listing creation rate continues to climb despite restriction" },
    ],
  },
  {
    title: "Regional data center loses primary and backup power",
    organisation: "Meridian Cloud",
    crisis_type: "INFRASTRUCTURE_FAILURE",
    incident_summary: "A storm knocked out grid power to a regional data center, and the backup generator failed to start, taking a full availability zone offline.",
    affected_users: "All customers with workloads pinned to the affected availability zone",
    reported_harm: "Extended downtime for customer applications with no cross-zone redundancy",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Failover customer traffic to the nearest healthy availability zone",
    known_constraints: "Not all customers have opted into cross-zone failover, risking data consistency issues for those who did not",
    evidence_summary: "Facilities incident log and generator diagnostic report",
    evidence: [{
      title: "Facilities power incident log",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Data_center",
      evidence_hash: "f2e6b9a3d1c74058",
      source_name: "Facilities operations",
      source_credibility_note: "Automated sensor logs plus on-site technician confirmation",
      relevance: "Confirms timeline of grid loss and generator failure",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Failover all traffic to nearest healthy zone", summary: "Redirect all customer traffic from the affected zone regardless of opt-in status.", action_type: "FAILOVER", expected_benefit: "Restores availability for the largest number of customers quickly", key_risk: "Customers without cross-zone replication may see data inconsistency", affected_stakeholders: "All customers in the affected zone", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Status page update and direct customer alert", failure_conditions: "Healthy zone cannot absorb the additional load" },
      { title: "Failover only opted-in customers", summary: "Redirect only customers who explicitly enabled cross-zone failover.", action_type: "SELECTIVE_FAILOVER", expected_benefit: "Avoids data consistency risk for customers who did not opt in", key_risk: "Non-opted-in customers remain fully down until power is restored", affected_stakeholders: "Opted-in customers restored; others remain down", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Status page update segmented by opt-in status", failure_conditions: "Power restoration takes longer than 4 hours" },
    ],
  },
  {
    title: "Background-check vendor breach exposes applicant records",
    organisation: "Talent Bridge HR",
    crisis_type: "VENDOR_BREACH",
    incident_summary: "A third-party background check vendor disclosed that applicant records processed on its platform were breached, including data for the company's job applicants.",
    affected_users: "Job applicants screened over the past 18 months, roughly 40,000",
    reported_harm: "Exposure of SSNs, criminal history records, and prior employment data",
    urgency_level: "HIGH",
    decision_deadline: "Within 24 hours",
    current_response_hypothesis: "Notify affected applicants and offer credit monitoring while assessing vendor liability",
    known_constraints: "Vendor has not yet confirmed the exact scope of records breached",
    evidence_summary: "Vendor breach disclosure notice and the data processing agreement scope",
    evidence: [{
      title: "Vendor breach disclosure notice",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Data_breach",
      evidence_hash: "a6c9e2b7f4d10583",
      source_name: "Vendor management team",
      source_credibility_note: "Official notice received from vendor's security team",
      relevance: "Confirms breach scope as disclosed by the vendor and affected data types",
      category: "LEGAL",
    }],
    response_options: [
      { title: "Notify applicants and offer credit monitoring", summary: "Send notice to all potentially affected applicants and provide free credit monitoring.", action_type: "DISCLOSURE_AND_REMEDY", expected_benefit: "Meets notification obligations and reduces harm to applicants", key_risk: "Vendor's incomplete scope confirmation may require a second notification later", affected_stakeholders: "Affected applicants, legal, vendor management", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Direct mail and email notice to affected applicants", failure_conditions: "Vendor later confirms a materially larger affected population" },
      { title: "Wait for vendor's final scope confirmation", summary: "Hold notification until the vendor confirms the exact final scope of the breach.", action_type: "WAIT_FOR_CONFIRMATION", expected_benefit: "Avoids sending multiple confusing notifications to applicants", key_risk: "Delayed notice may breach statutory notification deadlines", affected_stakeholders: "Affected applicants, legal", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None until scope confirmed", failure_conditions: "Statutory notification deadline passes before vendor confirms scope" },
    ],
  },
  {
    title: "Viral post falsely claims product causes serious harm",
    organisation: "Nordlight Skincare",
    crisis_type: "MISINFORMATION",
    incident_summary: "A viral social media post falsely claimed a flagship skincare product caused severe chemical burns, based on a fabricated lab result.",
    affected_users: "General public and existing customers",
    reported_harm: "Reputational damage and a sharp drop in sales following the post",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 8 hours",
    current_response_hypothesis: "Publish real third-party lab results and request platform takedown of the fabricated claim",
    known_constraints: "Takedown requests can take days to process on some platforms",
    evidence_summary: "Independent lab safety results and the original viral post with its fabricated attachment",
    evidence: [{
      title: "Third-party product safety lab results",
      evidence_type: "LAB_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Misinformation",
      evidence_hash: "c3f7a1d9b6e02458",
      source_name: "Independent cosmetics safety lab",
      source_credibility_note: "Accredited lab, results dated prior to the viral claim",
      relevance: "Directly contradicts the fabricated harm claim in the viral post",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Publish rebuttal with real lab data and request takedown", summary: "Release the genuine lab results publicly and file a platform takedown request for the false claim.", action_type: "PUBLIC_REBUTTAL", expected_benefit: "Directly counters the misinformation with verifiable evidence", key_risk: "Rebuttal could draw more attention to the original claim (Streisand effect)", affected_stakeholders: "Customers, general public", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Public statement and platform takedown request", failure_conditions: "Platform declines the takedown request" },
      { title: "Monitor without public rebuttal", summary: "Track the post's spread and only respond if it crosses a significant reach threshold.", action_type: "MONITOR", expected_benefit: "Avoids amplifying a claim that may fade on its own", key_risk: "Claim continues to spread unchecked, causing further sales impact", affected_stakeholders: "Customers, general public", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Post reach exceeds 1 million views without a response" },
    ],
  },
  {
    title: "Chemical spill at manufacturing plant reaches storm drain",
    organisation: "Cobalt Materials",
    crisis_type: "ENVIRONMENTAL_INCIDENT",
    incident_summary: "A valve failure released an estimated 400 gallons of a solvent into a storm drain connected to a nearby creek.",
    affected_users: "Downstream residents and local wildlife",
    reported_harm: "Potential water contamination and ecological damage",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Deploy containment booms at the discharge point and notify environmental authorities",
    known_constraints: "Exact solvent concentration reaching the creek has not yet been measured",
    evidence_summary: "Plant incident log and initial water sampling results near the discharge point",
    evidence: [{
      title: "Initial water sampling results",
      evidence_type: "LAB_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Chemical_spill",
      evidence_hash: "d8b2f5a9c1e60374",
      source_name: "Environmental compliance team",
      source_credibility_note: "First-hand sampling, lab confirmation pending",
      relevance: "Confirms detectable solvent presence at the discharge point",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Deploy containment and notify authorities immediately", summary: "Deploy booms at the discharge point and file a mandatory notification with environmental authorities.", action_type: "CONTAINMENT_AND_DISCLOSURE", expected_benefit: "Limits further spread and meets legal notification obligations", key_risk: "Public notification may trigger media attention before full facts are known", affected_stakeholders: "Downstream residents, regulators, plant staff", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Regulatory notification and community notice", failure_conditions: "Containment booms fail to stop further downstream migration" },
      { title: "Contain and internally assess before regulator notice", summary: "Deploy containment first and delay regulator notification until concentration is confirmed.", action_type: "CONTAINMENT_ONLY", expected_benefit: "Avoids a premature notification based on incomplete data", key_risk: "May breach mandatory notification timelines under environmental law", affected_stakeholders: "Downstream residents, plant staff", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "None until concentration confirmed", failure_conditions: "Mandatory notification deadline passes before concentration is confirmed" },
    ],
  },
  {
    title: "Warehouse staff walk out over safety concerns",
    organisation: "Ridgeline Logistics",
    crisis_type: "LABOR_DISPUTE",
    incident_summary: "Roughly 60% of second-shift warehouse staff walked out citing unresolved safety concerns following a prior injury incident.",
    affected_users: "Second-shift operations and downstream shipping commitments",
    reported_harm: "Operational disruption and risk of further labor action spreading to other shifts",
    urgency_level: "HIGH",
    decision_deadline: "Within 6 hours",
    current_response_hypothesis: "Meet with worker representatives immediately and commit to an expedited safety audit",
    known_constraints: "Cannot guarantee specific safety fixes without completing the audit first",
    evidence_summary: "Worker petition listing specific safety concerns and shift attendance records",
    evidence: [{
      title: "Worker safety concern petition",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Occupational_safety_and_health",
      evidence_hash: "7e1a4c9d3f60b285",
      source_name: "HR and employee relations",
      source_credibility_note: "First-hand petition signed by walkout participants",
      relevance: "Lists the specific safety issues cited as the reason for the walkout",
      category: "OPERATIONAL",
    }],
    response_options: [
      { title: "Meet with representatives and commit to expedited audit", summary: "Convene an immediate meeting with worker representatives and commit to a safety audit within 48 hours.", action_type: "NEGOTIATION", expected_benefit: "De-escalates the immediate dispute and addresses root safety concerns", key_risk: "Audit may reveal costly fixes beyond immediate budget", affected_stakeholders: "Warehouse staff, operations, HR", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Direct meeting and internal staff communication", failure_conditions: "Workers reject the audit commitment as insufficient" },
      { title: "Bring in temporary staff to maintain operations", summary: "Use a staffing agency to cover the shift while separately addressing worker concerns.", action_type: "OPERATIONAL_CONTINUITY", expected_benefit: "Maintains shipping commitments during the dispute", key_risk: "May be seen as strikebreaking and escalate tensions further", affected_stakeholders: "Warehouse staff, temporary workers, operations", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only", failure_conditions: "Walkout spreads to additional shifts in response" },
    ],
  },
  {
    title: "Senior executive accused of undisclosed conflict of interest",
    organisation: "Ashgrove Capital",
    crisis_type: "EXECUTIVE_MISCONDUCT",
    incident_summary: "A whistleblower alleges a senior executive approved vendor contracts with a company in which they held an undisclosed financial stake.",
    affected_users: "Shareholders and the vendor's competitors who lost the bids",
    reported_harm: "Potential fiduciary breach and reputational risk if substantiated",
    urgency_level: "HIGH",
    decision_deadline: "Within 3 business days",
    current_response_hypothesis: "Launch an independent investigation and place the executive on administrative leave pending findings",
    known_constraints: "Allegation is currently uncorroborated beyond the whistleblower's statement",
    evidence_summary: "Whistleblower complaint and vendor contract approval records",
    evidence: [{
      title: "Whistleblower complaint document",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Conflict_of_interest",
      evidence_hash: "9c4f7a2e1b8d0653",
      source_name: "Ethics hotline",
      source_credibility_note: "Anonymous submission, not yet independently corroborated",
      relevance: "Specifies the alleged financial stake and the contracts in question",
      category: "COMPLIANCE",
    }],
    response_options: [
      { title: "Independent investigation with administrative leave", summary: "Launch an independent investigation and place the executive on leave during the process.", action_type: "INVESTIGATE_AND_ISOLATE", expected_benefit: "Protects investigation integrity and signals seriousness to shareholders", key_risk: "Reputational harm to the executive if allegations are later unsubstantiated", affected_stakeholders: "Shareholders, board, the executive", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Board notification, no public statement yet", failure_conditions: "Investigation cannot be completed within a reasonable timeframe" },
      { title: "Internal review without administrative leave", summary: "Conduct an internal review while the executive continues normal duties.", action_type: "INVESTIGATE_ONLY", expected_benefit: "Avoids reputational harm from a leave if allegations are unfounded", key_risk: "Executive retains access to relevant records and approvals during review", affected_stakeholders: "Shareholders, board, the executive", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Board notification only", failure_conditions: "Executive is found to have influenced evidence during the review" },
    ],
  },
  {
    title: "Loan approval model shown to disadvantage protected group",
    organisation: "Keystone Lending",
    crisis_type: "ALGORITHMIC_BIAS",
    incident_summary: "An internal fairness audit found the automated loan approval model approved applicants from one demographic group at a materially lower rate after controlling for creditworthiness.",
    affected_users: "Loan applicants from the affected demographic group over the model's deployment period",
    reported_harm: "Potential discriminatory lending outcomes and regulatory exposure",
    urgency_level: "HIGH",
    decision_deadline: "Within 5 business days",
    current_response_hypothesis: "Suspend the automated model and revert to manual underwriting while the model is corrected",
    known_constraints: "Manual underwriting has significantly lower throughput than the automated model",
    evidence_summary: "Internal fairness audit statistical report",
    evidence: [{
      title: "Fairness audit statistical report",
      evidence_type: "AUDIT_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Algorithmic_bias",
      evidence_hash: "1f6b9c3e7a2d0584",
      source_name: "Model risk management team",
      source_credibility_note: "Internal audit using standard statistical parity and disparate impact tests",
      relevance: "Quantifies the approval rate gap after controlling for credit factors",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Suspend the model and revert to manual underwriting", summary: "Immediately stop using the automated model for approvals and process applications manually.", action_type: "SUSPEND_AND_REMEDIATE", expected_benefit: "Stops the discriminatory pattern immediately while a fix is developed", key_risk: "Manual underwriting backlog could delay legitimate applicants significantly", affected_stakeholders: "All loan applicants, underwriting staff, compliance", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Internal only, compliance filing as required", failure_conditions: "Manual backlog exceeds regulatory response time requirements" },
      { title: "Apply a statistical correction factor while investigating", summary: "Apply an interim adjustment to reduce the disparity while root-causing the model issue.", action_type: "INTERIM_MITIGATION", expected_benefit: "Reduces harm without a full throughput loss from manual review", key_risk: "An interim patch may not fully resolve the underlying bias and could mask it", affected_stakeholders: "All loan applicants, model risk team", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only", failure_conditions: "Correction factor is later found to be statistically inadequate" },
    ],
  },
  {
    title: "Nation-state actor suspected in network intrusion",
    organisation: "Ferrovia Energy",
    crisis_type: "CYBER_ATTACK",
    incident_summary: "Security monitoring detected lateral movement consistent with a known nation-state threat actor inside the corporate network, with proximity to operational technology segments.",
    affected_users: "Internal IT and OT systems; potentially regional power grid operations",
    reported_harm: "Risk of operational technology compromise affecting grid reliability",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Segment the OT network from IT immediately and engage national cybersecurity authorities",
    known_constraints: "Full network segmentation may briefly disrupt legitimate IT-OT data flows used for monitoring",
    evidence_summary: "Threat intelligence match report and network traffic logs showing lateral movement",
    evidence: [{
      title: "Threat intelligence and lateral movement report",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Cyberattack",
      evidence_hash: "6a2e9c4f1d7b0358",
      source_name: "Security operations center",
      source_credibility_note: "Automated detection cross-referenced with threat intelligence feed",
      relevance: "Confirms indicators of compromise matching a known threat actor's tooling",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Segment OT network and notify authorities immediately", summary: "Isolate OT systems from IT network and contact national cybersecurity authorities.", action_type: "CONTAINMENT_AND_DISCLOSURE", expected_benefit: "Protects critical infrastructure and enables coordinated response", key_risk: "Brief disruption to legitimate monitoring data flows", affected_stakeholders: "Grid operations, regional customers, authorities", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Authority notification, no public statement yet", failure_conditions: "Segmentation cannot be completed before further lateral movement" },
      { title: "Monitor covertly before segmentation", summary: "Continue silent monitoring to gather more intelligence before taking containment action.", action_type: "MONITOR_FIRST", expected_benefit: "Gathers more evidence on attacker intent and scope", key_risk: "Delay increases risk of OT compromise before containment", affected_stakeholders: "Grid operations, security team", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "None externally", failure_conditions: "Attacker reaches OT systems before containment begins" },
    ],
  },
  {
    title: "Unauthorized individual gains access to server room",
    organisation: "Cascade Family Parks",
    crisis_type: "PHYSICAL_SECURITY",
    incident_summary: "A security guard found an unbadged individual inside the corporate server room after hours; the individual fled before being identified.",
    affected_users: "IT systems and any data accessible from the server room",
    reported_harm: "Unknown — potential tampering or data access, not yet confirmed",
    urgency_level: "HIGH",
    decision_deadline: "Within 4 hours",
    current_response_hypothesis: "Audit server room access logs and physical equipment for tampering, rotate access credentials as a precaution",
    known_constraints: "Camera footage of the individual's face is inconclusive due to poor lighting",
    evidence_summary: "Security guard incident report and door badge access log",
    evidence: [{
      title: "Security guard incident report",
      evidence_type: "INCIDENT_REPORT",
      evidence_url: "https://en.wikipedia.org/wiki/Physical_security",
      evidence_hash: "3d7a1e9c4f0b6852",
      source_name: "Physical security team",
      source_credibility_note: "First-hand account from the responding guard",
      relevance: "Confirms the approximate time window and entry point used",
      category: "OPERATIONAL",
    }],
    response_options: [
      { title: "Audit and rotate credentials immediately", summary: "Inspect all server room equipment for tampering and rotate access credentials as a precaution.", action_type: "CONTAINMENT", expected_benefit: "Limits damage from any credential compromise or tampering", key_risk: "Credential rotation may briefly disrupt legitimate access", affected_stakeholders: "IT staff, security team", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Internal security bulletin", failure_conditions: "Tampering is found on equipment that cannot be immediately isolated" },
      { title: "Full facility lockdown and law enforcement notification", summary: "Lock down the facility and notify local law enforcement before resuming normal access.", action_type: "ESCALATED_CONTAINMENT", expected_benefit: "Maximizes chance of identifying and apprehending the intruder", key_risk: "Significant operational disruption to the broader facility", affected_stakeholders: "All facility staff, security team, law enforcement", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal staff notice", failure_conditions: "Lockdown extends beyond the operational window without new information" },
    ],
  },
  {
    title: "Critical SaaS dependency suffers extended outage",
    organisation: "Solstice Electronics",
    crisis_type: "THIRD_PARTY_OUTAGE",
    incident_summary: "The customer support ticketing platform used company-wide went down for 14 hours, blocking all support ticket creation and updates.",
    affected_users: "Customers attempting to file or check support tickets",
    reported_harm: "Delayed support response for customers with active issues",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 6 hours",
    current_response_hypothesis: "Stand up a temporary email-based support channel until the vendor restores service",
    known_constraints: "Temporary channel will not have the same triage automation as the primary platform",
    evidence_summary: "Vendor status page and internal support queue metrics",
    evidence: [{
      title: "Vendor status page history",
      evidence_type: "LOG",
      evidence_url: "https://en.wikipedia.org/wiki/Software_as_a_service",
      evidence_hash: "5b8e2a7c9f1d0463",
      source_name: "IT operations",
      source_credibility_note: "Vendor's own public status page, cross-checked against internal reports",
      relevance: "Confirms outage duration and vendor's stated cause",
      category: "TECHNICAL",
    }],
    response_options: [
      { title: "Stand up a temporary email support channel", summary: "Redirect customers to a dedicated email address staffed manually until the platform recovers.", action_type: "CONTINGENCY", expected_benefit: "Maintains some support capability during the outage", key_risk: "Manual triage is slower and may lose ticket context", affected_stakeholders: "Customers with active issues, support staff", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Support page banner with the temporary contact method", failure_conditions: "Email volume exceeds what the team can triage manually" },
      { title: "Wait for vendor recovery without a temporary channel", summary: "Post a status notice and wait for the vendor to restore service without standing up an alternative.", action_type: "WAIT", expected_benefit: "Avoids the overhead of standing up and later tearing down a temporary process", key_risk: "Customers with urgent issues have no way to reach support during the outage", affected_stakeholders: "Customers with active issues", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Status page notice only", failure_conditions: "Outage extends beyond 24 hours" },
    ],
  },
  {
    title: "Former employee threatens legal action over wrongful termination",
    organisation: "Ashgrove Capital",
    crisis_type: "LEGAL_DISPUTE",
    incident_summary: "A recently terminated employee sent a formal letter alleging wrongful termination in retaliation for a compliance complaint, threatening litigation.",
    affected_users: "The former employee and the compliance function's credibility",
    reported_harm: "Potential legal liability and reputational risk if retaliation is substantiated",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 5 business days",
    current_response_hypothesis: "Engage outside employment counsel and place a litigation hold on relevant records",
    known_constraints: "The termination decision was made by a manager who was not aware of the prior compliance complaint",
    evidence_summary: "Termination documentation and timeline of the compliance complaint relative to the termination decision",
    evidence: [{
      title: "Termination timeline and complaint records",
      evidence_type: "DOCUMENT",
      evidence_url: "https://en.wikipedia.org/wiki/Wrongful_dismissal",
      evidence_hash: "0e4c8a1f7b2d6935",
      source_name: "HR records",
      source_credibility_note: "Internal records, timestamps verified against HR system logs",
      relevance: "Establishes the sequence of events between the complaint and termination decision",
      category: "LEGAL",
    }],
    response_options: [
      { title: "Engage outside counsel and issue a litigation hold", summary: "Retain outside employment counsel and formally preserve all relevant records.", action_type: "LEGAL_PREPAREDNESS", expected_benefit: "Positions the company well for either settlement or litigation", key_risk: "Signals to the former employee that the company is taking the threat seriously, which could encourage escalation", affected_stakeholders: "Legal, HR, the former employee", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Internal only", failure_conditions: "Relevant records are found to have already been deleted per normal retention policy" },
      { title: "Attempt direct settlement discussion first", summary: "Reach out directly to the former employee to explore an early resolution before formal legal engagement.", action_type: "EARLY_RESOLUTION", expected_benefit: "May resolve the matter faster and at lower cost than litigation", key_risk: "Direct contact without counsel present could create additional legal exposure", affected_stakeholders: "Legal, HR, the former employee", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Direct outreach to former employee", failure_conditions: "Former employee's counsel advises against any direct contact" },
    ],
  },
  {
    title: "Coastal facility in path of an approaching hurricane",
    organisation: "Meridian Cloud",
    crisis_type: "NATURAL_DISASTER_RESPONSE",
    incident_summary: "A Category 3 hurricane is projected to make landfall within 36 hours near a coastal data center that lacks full flood mitigation for storm surge levels forecast.",
    affected_users: "Customers with workloads hosted at the coastal facility",
    reported_harm: "Risk of extended outage or permanent data loss if flooding occurs",
    urgency_level: "CRITICAL",
    decision_deadline: "Within 12 hours",
    current_response_hypothesis: "Begin an orderly failover of all workloads to an inland facility before landfall",
    known_constraints: "Full failover of all workloads typically takes 18-24 hours to complete safely",
    evidence_summary: "National weather service storm track forecast and facility flood mitigation assessment",
    evidence: [{
      title: "Storm track and surge forecast",
      evidence_type: "FORECAST",
      evidence_url: "https://en.wikipedia.org/wiki/Hurricane",
      evidence_hash: "8f1c4a7e2d9b0356",
      source_name: "National weather service",
      source_credibility_note: "Official government forecast, updated every 6 hours",
      relevance: "Confirms projected landfall timing and expected storm surge height",
      category: "EXTERNAL",
    }],
    response_options: [
      { title: "Begin immediate full failover to inland facility", summary: "Start the 18-24 hour failover process for all workloads now, ahead of the forecast landfall.", action_type: "PROACTIVE_FAILOVER", expected_benefit: "Maximizes the chance of completing failover before the storm arrives", key_risk: "Failover may not fully complete for all customers before landfall", affected_stakeholders: "All customers hosted at the coastal facility", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Customer advisory with failover timeline", failure_conditions: "Failover is still incomplete for a significant customer segment at landfall" },
      { title: "Wait for a more confident forecast before failover", summary: "Delay failover until the storm track forecast narrows further, reducing risk of an unnecessary failover.", action_type: "WAIT_AND_MONITOR", expected_benefit: "Avoids the operational cost and risk of an unnecessary failover if the storm shifts track", key_risk: "A narrower window increases the chance failover cannot complete before landfall", affected_stakeholders: "All customers hosted at the coastal facility", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Customer advisory noting the storm is being monitored", failure_conditions: "Forecast confidence does not improve until fewer than 12 hours remain" },
    ],
  },
];
