// 20 crisis scenarios deliberately biased across all 5 response_proportionality
// tiers (4 per tier) so the seeded contract shows real variety in verdict
// severity, not just uniformly critical cases. Content ranges from a
// non-issue (NO_ACTION_NEEDED) up to a catastrophic emergency
// (EMERGENCY_SHUTDOWN). Actual verdicts are produced by a real LLM and are
// not guaranteed to land exactly as intended, but the bias is strong.

export const scenarios20 = [
  // --- Tier: NO_ACTION_NEEDED --------------------------------------------
  {
    tier: "NO_ACTION_NEEDED",
    title: "Positive feedback message misfiled as an incident ticket",
    organisation: "Northwind Retail",
    crisis_type: "MISCATEGORIZED_TICKET",
    incident_summary: "A customer's glowing feedback about a recent purchase was auto-tagged as a 'critical' ticket by a keyword-matching filter that misfired on the word 'blew me away'.",
    affected_users: "1 customer, no actual impact",
    reported_harm: "None — the ticket is positive feedback, not a complaint",
    urgency_level: "LOW",
    decision_deadline: "No deadline",
    current_response_hypothesis: "Close the ticket as miscategorized and thank the customer",
    known_constraints: "None",
    evidence_summary: "Full text of the ticket confirming it is positive feedback",
    evidence: [{ title: "Ticket transcript", evidence_type: "DOCUMENT", evidence_url: "https://en.wikipedia.org/wiki/Customer_service", evidence_hash: "a1b1c1d1e1f10101", source_name: "Support system", source_credibility_note: "Verbatim ticket text", relevance: "Confirms the message is positive feedback, not an incident", category: "OPERATIONAL" }],
    response_options: [
      { title: "Close as miscategorized, thank the customer", summary: "Reclassify the ticket and send a short thank-you reply.", action_type: "NO_ACTION", expected_benefit: "Resolves the misfile with a positive customer touchpoint", key_risk: "None", affected_stakeholders: "Support team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Reply to the customer", failure_conditions: "None expected" },
      { title: "Tune the keyword filter", summary: "Adjust the auto-tagging filter to avoid this false-positive pattern.", action_type: "PRECAUTIONARY", expected_benefit: "Reduces future miscategorizations", key_risk: "Minor engineering time for a low-impact fix", affected_stakeholders: "Support team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "New filter introduces different false positives" },
    ],
  },
  {
    tier: "NO_ACTION_NEEDED",
    title: "Scheduled maintenance window mistaken for an outage",
    organisation: "Meridian Cloud",
    crisis_type: "USER_MISUNDERSTANDING",
    incident_summary: "One customer reported an 'outage' during a pre-announced 5-minute maintenance window that had been communicated two weeks in advance via email and status page.",
    affected_users: "1 customer inquiry",
    reported_harm: "None — service behaved exactly as scheduled and announced",
    urgency_level: "LOW",
    decision_deadline: "No deadline",
    current_response_hypothesis: "Point the customer to the prior announcement and status page history",
    known_constraints: "None",
    evidence_summary: "Maintenance announcement email and status page history",
    evidence: [{ title: "Maintenance announcement and status page log", evidence_type: "DOCUMENT", evidence_url: "https://en.wikipedia.org/wiki/Scheduled_maintenance", evidence_hash: "b2c2d2e2f2021212", source_name: "Status page archive", source_credibility_note: "Timestamped, publicly archived announcement", relevance: "Confirms the window was pre-announced and matches the customer's report time", category: "OPERATIONAL" }],
    response_options: [
      { title: "Reply with the maintenance history, no other action", summary: "Send the customer the announcement and status page links.", action_type: "NO_ACTION", expected_benefit: "Resolves the misunderstanding with no engineering involvement", key_risk: "None", affected_stakeholders: "Support team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Reply to the customer", failure_conditions: "None expected" },
      { title: "Improve maintenance-window in-app banners", summary: "Add a more visible in-app banner during future maintenance windows.", action_type: "PRECAUTIONARY", expected_benefit: "Reduces future confusion for other customers", key_risk: "Minor design/engineering effort for a rare occurrence", affected_stakeholders: "All customers", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "Banner is not ready before the next scheduled window" },
    ],
  },
  {
    tier: "NO_ACTION_NEEDED",
    title: "Cosmetic typo reported on a marketing landing page",
    organisation: "Nordlight Skincare",
    crisis_type: "COSMETIC_DEFECT",
    incident_summary: "A user reported a typo ('recieve' instead of 'receive') in the footer of a marketing landing page. No functional impact.",
    affected_users: "Anyone viewing the page, cosmetic only",
    reported_harm: "None",
    urgency_level: "LOW",
    decision_deadline: "No deadline",
    current_response_hypothesis: "Fix the typo in the next routine content update",
    known_constraints: "None",
    evidence_summary: "Screenshot of the page showing the typo",
    evidence: [{ title: "Page screenshot with typo highlighted", evidence_type: "DOCUMENT", evidence_url: "https://en.wikipedia.org/wiki/Typographical_error", evidence_hash: "c3d3e3f303131313", source_name: "Marketing team", source_credibility_note: "Directly observed on the live page", relevance: "Confirms the typo and its cosmetic-only nature", category: "OPERATIONAL" }],
    response_options: [
      { title: "Fix in next routine content update", summary: "Correct the typo during the next scheduled content push.", action_type: "NO_ACTION", expected_benefit: "Resolves the cosmetic issue at no extra cost", key_risk: "None", affected_stakeholders: "Marketing team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "None expected" },
      { title: "Hotfix the typo immediately", summary: "Push an out-of-cycle fix for the single typo right away.", action_type: "PRECAUTIONARY", expected_benefit: "Removes the typo from public view sooner", key_risk: "Unnecessary deployment overhead for a cosmetic issue", affected_stakeholders: "Marketing team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "Hotfix deployment introduces an unrelated regression" },
    ],
  },
  {
    tier: "NO_ACTION_NEEDED",
    title: "Fraud alert falsely flagged a routine $12 purchase",
    organisation: "Fenwick Pay",
    crisis_type: "FALSE_POSITIVE_ALERT",
    incident_summary: "The fraud detection system flagged a routine $12 coffee shop purchase as suspicious due to a rare merchant category code; manual review confirmed it was legitimate within minutes.",
    affected_users: "1 customer, transaction was approved after brief manual review",
    reported_harm: "None — transaction ultimately succeeded with a short delay",
    urgency_level: "LOW",
    decision_deadline: "No deadline",
    current_response_hypothesis: "No action needed; this is normal false-positive behavior for a rare merchant code",
    known_constraints: "None",
    evidence_summary: "Fraud system log showing the flag and subsequent manual approval",
    evidence: [{ title: "Fraud system flag and approval log", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Fraud_detection", evidence_hash: "d4e4f4041414141", source_name: "Fraud detection system", source_credibility_note: "Automated log, consistent with known false-positive rate for rare merchant codes", relevance: "Confirms this is an isolated, already-resolved false positive", category: "TECHNICAL" }],
    response_options: [
      { title: "No action, this is expected system behavior", summary: "Log the case as a normal false positive with no further action.", action_type: "NO_ACTION", expected_benefit: "Avoids unnecessary changes to a working fraud model", key_risk: "None", affected_stakeholders: "Fraud team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "None expected" },
      { title: "Add the merchant code to a lower-risk allowlist", summary: "Reduce the risk score for this specific rare-but-legitimate merchant category.", action_type: "PRECAUTIONARY", expected_benefit: "Slightly fewer false positives for this merchant type going forward", key_risk: "Could very marginally reduce fraud detection sensitivity for that category", affected_stakeholders: "Fraud team, cardholders", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Allowlisting is later exploited for actual fraud using that merchant code" },
    ],
  },

  // --- Tier: MONITORING_SUFFICIENT ----------------------------------------
  {
    tier: "MONITORING_SUFFICIENT",
    title: "Slightly elevated latency on a non-critical reporting API",
    organisation: "Meridian Cloud",
    crisis_type: "MINOR_PERFORMANCE_DEGRADATION",
    incident_summary: "The internal analytics reporting API (not customer-facing) is running about 300ms slower than baseline over the past 6 hours, with no errors and no customer-facing impact.",
    affected_users: "Internal analytics team only",
    reported_harm: "Slightly slower internal dashboards, no customer impact",
    urgency_level: "LOW",
    decision_deadline: "Within 2 days",
    current_response_hypothesis: "Monitor the trend; investigate only if latency continues climbing",
    known_constraints: "None",
    evidence_summary: "Latency trend graph for the reporting API over the past week",
    evidence: [{ title: "Reporting API latency dashboard", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Latency_(engineering)", evidence_hash: "e5f5051515151515", source_name: "Internal monitoring", source_credibility_note: "Automated, high confidence", relevance: "Confirms the latency increase is real but modest and isolated to a non-critical internal API", category: "TECHNICAL" }],
    response_options: [
      { title: "Monitor the trend for 48 more hours", summary: "Keep watching the latency graph before taking any engineering action.", action_type: "MONITOR", expected_benefit: "Avoids premature engineering effort for a possibly transient blip", key_risk: "Latency could continue degrading unnoticed if trend accelerates", affected_stakeholders: "Internal analytics team", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Latency continues to climb past twice the current level" },
      { title: "Open a low-priority investigation ticket now", summary: "File a ticket for the on-call team to investigate during normal working hours.", action_type: "SCHEDULED_INVESTIGATION", expected_benefit: "Gets a root cause identified sooner without urgent escalation", key_risk: "Minor engineering time spent on a non-customer-facing issue", affected_stakeholders: "Internal analytics team, on-call engineer", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Root cause is not found within the sprint" },
    ],
  },
  {
    tier: "MONITORING_SUFFICIENT",
    title: "Small batch of low-priority notifications delayed by 20 minutes",
    organisation: "Orbital Streaming",
    crisis_type: "MINOR_SERVICE_DELAY",
    incident_summary: "About 2,000 non-urgent 'new episode available' push notifications were delayed by roughly 20 minutes due to a queue backlog, with no other notification types affected.",
    affected_users: "Roughly 2,000 subscribers",
    reported_harm: "Minor inconvenience — a slightly delayed non-urgent notification",
    urgency_level: "LOW",
    decision_deadline: "Within 24 hours",
    current_response_hypothesis: "Monitor the notification queue depth; no customer-facing action needed",
    known_constraints: "None",
    evidence_summary: "Notification queue depth graph showing the temporary backlog",
    evidence: [{ title: "Notification queue depth graph", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Push_technology", evidence_hash: "f6061616161616", source_name: "Notification service monitoring", source_credibility_note: "Automated, high confidence", relevance: "Confirms the backlog was temporary and limited to non-urgent notifications", category: "TECHNICAL" }],
    response_options: [
      { title: "Monitor the queue, no customer communication needed", summary: "Continue tracking queue depth without notifying subscribers.", action_type: "MONITOR", expected_benefit: "Avoids overcommunicating about a minor, already-resolving delay", key_risk: "A subset of subscribers may notice the delay independently", affected_stakeholders: "Subscribers, notification team", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Backlog recurs and grows to affect urgent notification types" },
      { title: "Add queue capacity as a precaution", summary: "Scale up notification worker capacity to reduce the chance of recurrence.", action_type: "PRECAUTIONARY", expected_benefit: "Reduces likelihood of a repeat backlog", key_risk: "Modest additional infrastructure cost", affected_stakeholders: "Notification team", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Backlog recurs despite the added capacity" },
    ],
  },
  {
    tier: "MONITORING_SUFFICIENT",
    title: "One node in a redundant cluster running hot",
    organisation: "Ferrovia Energy",
    crisis_type: "MINOR_INFRASTRUCTURE_ANOMALY",
    incident_summary: "One of six redundant application servers is running at 85% CPU versus a normal 40-50% baseline for the other five; overall service is unaffected due to load balancing.",
    affected_users: "None currently — service is unaffected",
    reported_harm: "None currently",
    urgency_level: "LOW",
    decision_deadline: "Within 24 hours",
    current_response_hypothesis: "Monitor the hot node; drain and investigate if it approaches capacity limits",
    known_constraints: "None",
    evidence_summary: "Per-node CPU utilization graph across the cluster",
    evidence: [{ title: "Cluster CPU utilization by node", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Load_balancing_(computing)", evidence_hash: "071717171717171", source_name: "Infrastructure monitoring", source_credibility_note: "Automated, high confidence", relevance: "Confirms one node is anomalously hot while overall service remains healthy", category: "TECHNICAL" }],
    response_options: [
      { title: "Monitor the node, no action yet", summary: "Continue watching CPU trend on the affected node.", action_type: "MONITOR", expected_benefit: "Avoids unnecessary node cycling for what may be a transient load imbalance", key_risk: "Node could approach capacity if trend continues", affected_stakeholders: "Infrastructure team", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None", failure_conditions: "Node CPU exceeds 95% sustained" },
      { title: "Proactively drain and restart the hot node", summary: "Take the node out of rotation, restart it, and reintroduce it to the cluster.", action_type: "PRECAUTIONARY", expected_benefit: "Resolves the anomaly before it risks becoming customer-facing", key_risk: "Briefly reduces cluster redundancy during the drain", affected_stakeholders: "Infrastructure team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None", failure_conditions: "CPU anomaly recurs on the same node after restart" },
    ],
  },
  {
    tier: "MONITORING_SUFFICIENT",
    title: "Isolated complaint about search result relevance",
    organisation: "Marketplace Nine",
    crisis_type: "MINOR_QUALITY_COMPLAINT",
    incident_summary: "A single seller complained that search results for their product category seemed less relevant after a recent ranking algorithm update, though metrics show no aggregate change in click-through rate.",
    affected_users: "1 seller's reported perception; no measurable aggregate impact",
    reported_harm: "Perceived, not measured — aggregate search metrics are stable",
    urgency_level: "LOW",
    decision_deadline: "Within 1 week",
    current_response_hypothesis: "Monitor search quality metrics for this category specifically before making changes",
    known_constraints: "None",
    evidence_summary: "Aggregate search click-through rate before and after the ranking update",
    evidence: [{ title: "Search CTR trend before/after ranking update", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Search_engine", evidence_hash: "1828282828282828", source_name: "Search analytics", source_credibility_note: "Automated, high confidence, but limited to aggregate — not category-specific", relevance: "Shows no aggregate degradation, though category-level data is not yet broken out", category: "TECHNICAL" }],
    response_options: [
      { title: "Monitor category-specific search metrics", summary: "Break out search quality metrics for this specific category before deciding on any change.", action_type: "MONITOR", expected_benefit: "Avoids reverting a beneficial algorithm change based on one report", key_risk: "A genuine category-specific regression could persist a bit longer", affected_stakeholders: "Sellers in this category, search team", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "Acknowledge the seller's report", failure_conditions: "Category-specific data confirms a real regression" },
      { title: "Revert the ranking update for this category only", summary: "Roll back the ranking algorithm change specifically for the affected category.", action_type: "TARGETED_ROLLBACK", expected_benefit: "Immediately addresses the seller's concern if it is valid", key_risk: "Reverts a change that aggregate data suggests may be fine or beneficial", affected_stakeholders: "Sellers in this category, buyers, search team", time_sensitivity: "STANDARD", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Notify the seller of the change", failure_conditions: "Reverting does not address the seller's underlying concern" },
    ],
  },

  // --- Tier: TARGETED_ACTION_REQUIRED --------------------------------------
  {
    tier: "TARGETED_ACTION_REQUIRED",
    title: "Checkout errors affecting a subset of users on one payment method",
    organisation: "Lumen Commerce",
    crisis_type: "SERVICE_DEGRADATION",
    incident_summary: "Roughly 12% of checkout attempts using a specific regional payment method have failed over the past 3 hours; all other payment methods are working normally.",
    affected_users: "Approximately 3,000 customers using the affected payment method today",
    reported_harm: "Failed checkouts and abandoned carts for the affected payment method",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 8 hours",
    current_response_hypothesis: "Deploy a targeted fix to the affected payment method's integration",
    known_constraints: "Disabling the payment method entirely would fully block a significant customer segment",
    evidence_summary: "Checkout success rate by payment method over the past 24 hours",
    evidence: [{ title: "Checkout success rate by payment method", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Payment_processor", evidence_hash: "293939393939393", source_name: "Checkout monitoring", source_credibility_note: "Automated, high confidence", relevance: "Confirms the failure is isolated to one payment method's integration", category: "TECHNICAL" }],
    response_options: [
      { title: "Deploy a targeted fix to the affected integration", summary: "Patch the specific payment method's integration code believed to be causing failures.", action_type: "TARGETED_FIX", expected_benefit: "Resolves the issue without disrupting other payment methods", key_risk: "Root cause may not be fully confirmed before the fix ships", affected_stakeholders: "Customers using the affected payment method", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Status page note for the affected payment method", failure_conditions: "Failure rate does not improve after the fix deploys" },
      { title: "Temporarily disable the affected payment method", summary: "Hide the payment method from checkout until the fix is ready.", action_type: "TEMPORARY_DISABLE", expected_benefit: "Prevents further failed attempts and abandoned carts", key_risk: "Fully blocks a payment option some customers may need", affected_stakeholders: "Customers using the affected payment method", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Checkout page notice", failure_conditions: "Customers cannot complete checkout with any alternative method" },
    ],
  },
  {
    tier: "TARGETED_ACTION_REQUIRED",
    title: "One product category page intermittently returning server errors",
    organisation: "Solstice Electronics",
    crisis_type: "SERVICE_DEGRADATION",
    incident_summary: "The 'Laptops' category page has returned intermittent 500 errors for about 6% of requests over the past 4 hours; all other category pages are unaffected.",
    affected_users: "Customers browsing the Laptops category, roughly 8,000 sessions",
    reported_harm: "Failed page loads requiring a retry; some customers may leave without browsing further",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 6 hours",
    current_response_hypothesis: "Roll back the recent change to the Laptops category page template",
    known_constraints: "The template change also includes an unrelated pricing display fix that would be lost on rollback",
    evidence_summary: "Error rate by category page and recent deployment log",
    evidence: [{ title: "Category page error rate and deployment log", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/HTTP_500", evidence_hash: "3a4a4a4a4a4a4a4a", source_name: "Web engineering team", source_credibility_note: "Automated error tracking correlated with deployment timestamps", relevance: "Confirms the errors began immediately after the Laptops template deploy", category: "TECHNICAL" }],
    response_options: [
      { title: "Roll back the Laptops page template", summary: "Revert the recent template change specifically for the Laptops category.", action_type: "TARGETED_ROLLBACK", expected_benefit: "Directly addresses the confirmed correlated cause", key_risk: "Loses the unrelated pricing display fix bundled in the same deploy", affected_stakeholders: "Customers browsing Laptops, web engineering, pricing team", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None to customers", failure_conditions: "Errors persist after rollback, indicating an unrelated cause" },
      { title: "Patch the specific template bug in place", summary: "Ship a scoped fix for the suspected bug without a full rollback.", action_type: "TARGETED_FIX", expected_benefit: "Preserves the pricing display fix while resolving the error", key_risk: "Takes longer to prepare and verify than a rollback", affected_stakeholders: "Customers browsing Laptops, web engineering", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "None to customers", failure_conditions: "Patch does not reduce the error rate within 2 hours" },
    ],
  },
  {
    tier: "TARGETED_ACTION_REQUIRED",
    title: "Discount code allowing repeated application beyond intended limit",
    organisation: "Marketplace Nine",
    crisis_type: "PRICING_LOGIC_BUG",
    incident_summary: "A promotional discount code intended for one-time use per account was found to be stackable due to a validation bug, applied multiple times by roughly 400 accounts before detection.",
    affected_users: "Roughly 400 accounts that exploited the bug; broader customer base unaffected",
    reported_harm: "Revenue loss from over-applied discounts; no harm to unaffected customers",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 4 hours",
    current_response_hypothesis: "Disable the specific promo code and patch the stacking validation bug",
    known_constraints: "Some of the 400 accounts may have stacked the discount unintentionally rather than through deliberate exploitation",
    evidence_summary: "Discount code usage log showing the abnormal repeat-application pattern",
    evidence: [{ title: "Discount code usage log", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Coupon", evidence_hash: "4b5b5b5b5b5b5b5b", source_name: "Pricing engine logs", source_credibility_note: "Automated, high confidence", relevance: "Confirms the validation bug and quantifies the affected account count", category: "TECHNICAL" }],
    response_options: [
      { title: "Disable the code and patch the validation bug", summary: "Immediately disable the specific promo code and fix the underlying stacking bug.", action_type: "TARGETED_FIX", expected_benefit: "Stops further revenue loss from this specific code", key_risk: "Other promo codes could have the same underlying bug, unaddressed for now", affected_stakeholders: "Pricing team, the 400 affected accounts", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "None to customers yet", failure_conditions: "The same validation bug is found on other active promo codes" },
      { title: "Audit all active promo codes for the same bug class", summary: "Pause all active promo codes while auditing the validation logic across the board.", action_type: "BROAD_INVESTIGATION", expected_benefit: "Catches any other codes with the same underlying flaw", key_risk: "Pausing all codes disrupts legitimate promotions unrelated to this bug", affected_stakeholders: "All customers using any active promo code, pricing team", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Notice on promo-eligible pages", failure_conditions: "Audit takes longer than the promo campaigns can afford to be paused" },
    ],
  },
  {
    tier: "TARGETED_ACTION_REQUIRED",
    title: "Regional shipping partner integration silently failing for one country",
    organisation: "Solstice Electronics",
    crisis_type: "INTEGRATION_FAILURE",
    incident_summary: "Orders shipping to one country have silently failed to generate shipping labels for the past 2 days due to a schema change on the shipping partner's API that was not caught by monitoring.",
    affected_users: "Roughly 600 orders destined for the affected country",
    reported_harm: "Delayed shipments with no automatic customer notification of the delay",
    urgency_level: "MEDIUM",
    decision_deadline: "Within 8 hours",
    current_response_hypothesis: "Deploy a fix for the shipping partner's schema change and manually process the backlogged orders",
    known_constraints: "Manual processing of 600 orders will take staff time away from other queues",
    evidence_summary: "Shipping label generation failure log for the affected country",
    evidence: [{ title: "Shipping API failure log", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Application_programming_interface", evidence_hash: "5c6c6c6c6c6c6c6c", source_name: "Logistics engineering team", source_credibility_note: "Automated error log correlated with the partner's API changelog", relevance: "Confirms the schema change is the cause and quantifies the backlog", category: "TECHNICAL" }],
    response_options: [
      { title: "Deploy the schema fix and manually clear the backlog", summary: "Patch the integration for the new schema and manually process the 600 affected orders.", action_type: "TARGETED_FIX", expected_benefit: "Resolves both the root cause and the existing backlog", key_risk: "Manual processing takes staff time and may still take a day to clear", affected_stakeholders: "Customers with affected orders, logistics team", time_sensitivity: "URGENT", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Delay notice to affected customers", failure_conditions: "Manual backlog cannot be cleared within 48 hours" },
      { title: "Temporarily route affected-country orders to a backup carrier", summary: "Fail over shipping for the affected country to a backup carrier while the fix is prepared.", action_type: "FAILOVER", expected_benefit: "Unblocks new orders immediately without waiting for the fix", key_risk: "Backup carrier may have higher rates or slower delivery for that country", affected_stakeholders: "Customers with orders to the affected country, logistics team", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "None if transparent to customers", failure_conditions: "Backup carrier cannot service the affected country either" },
    ],
  },

  // --- Tier: IMMEDIATE_INTERVENTION ----------------------------------------
  {
    tier: "IMMEDIATE_INTERVENTION",
    title: "Customer database exposed via misconfigured backup",
    organisation: "Northwind Retail",
    crisis_type: "DATA_BREACH",
    incident_summary: "A cloud storage bucket holding nightly customer database backups was left publicly readable for approximately 40 hours before discovery.",
    affected_users: "Roughly 2.1 million registered customers",
    reported_harm: "Exposure of names, emails, hashed passwords, and partial payment tokens",
    urgency_level: "CRITICAL",
    decision_deadline: "Within 2 hours",
    current_response_hypothesis: "Revoke public access immediately and force a password reset for all accounts",
    known_constraints: "Cannot take checkout offline during peak sales weekend",
    evidence_summary: "Security scanner alert plus access logs showing anonymous reads from multiple IP ranges",
    evidence: [{ title: "Access log excerpt showing anonymous bucket reads", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Data_breach", evidence_hash: "9f2a1c7e4b3d0f6a", source_name: "Internal SIEM", source_credibility_note: "Automated, cross-referenced with cloud provider audit trail", relevance: "Confirms unauthorized external access window and IP ranges involved", category: "TECHNICAL" }],
    response_options: [
      { title: "Force password reset and disclose within 2 hours", summary: "Immediately revoke bucket access, force resets, and publish a disclosure notice.", action_type: "CONTAINMENT_AND_DISCLOSURE", expected_benefit: "Limits credential reuse damage and meets regulatory disclosure windows", key_risk: "Reset flow may overload support channels", affected_stakeholders: "All registered customers, support team, legal", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Public status page notice plus direct email", failure_conditions: "Reset emails delayed beyond 4 hours" },
      { title: "Quiet containment pending forensics", summary: "Revoke access silently and wait for forensic confirmation before any disclosure.", action_type: "CONTAINMENT_ONLY", expected_benefit: "Avoids premature or inaccurate public statements", key_risk: "Delayed disclosure may violate breach notification laws", affected_stakeholders: "Legal, executive team", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only until forensics complete", failure_conditions: "Regulator or press learns of the breach before disclosure" },
    ],
  },
  {
    tier: "IMMEDIATE_INTERVENTION",
    title: "Ransomware encrypts internal file servers",
    organisation: "Briarwood Health Network",
    crisis_type: "SECURITY_INCIDENT",
    incident_summary: "A ransomware strain encrypted several internal file servers including scheduling systems, discovered by IT at 3am.",
    affected_users: "Internal staff across 6 clinic locations; indirectly, patients with scheduled appointments",
    reported_harm: "Operational disruption to appointment scheduling and records access",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Isolate affected servers from the network and switch to paper-based scheduling temporarily",
    known_constraints: "Cannot confirm yet whether patient records were exfiltrated before encryption",
    evidence_summary: "IT incident log and ransom note screenshot",
    evidence: [{ title: "Ransom note and encrypted file listing", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Ransomware", evidence_hash: "6d1f8a3c9e5b207f", source_name: "IT security team", source_credibility_note: "First-hand, captured at time of discovery", relevance: "Confirms scope of encrypted systems and ransom demand", category: "TECHNICAL" }],
    response_options: [
      { title: "Isolate and rebuild from backups", summary: "Disconnect affected servers, do not pay ransom, restore from the last clean backup.", action_type: "CONTAINMENT_AND_RECOVERY", expected_benefit: "Avoids funding attackers and restores clean systems", key_risk: "Backup may be days old, causing data loss", affected_stakeholders: "Clinic staff, patients", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal staff briefing, patient notice only if records affected", failure_conditions: "Backups are also found to be compromised" },
      { title: "Engage incident response firm before any action", summary: "Bring in an external IR firm to assess exfiltration risk before touching systems.", action_type: "INVESTIGATE_FIRST", expected_benefit: "Preserves forensic evidence and clarifies exfiltration scope", key_risk: "Extends downtime for clinics", affected_stakeholders: "Clinic staff, patients, legal", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Internal only during investigation", failure_conditions: "IR firm cannot be engaged within the operational window" },
    ],
  },
  {
    tier: "IMMEDIATE_INTERVENTION",
    title: "Coordinated account takeover ring drains user wallets",
    organisation: "Fenwick Pay",
    crisis_type: "FRAUD",
    incident_summary: "A credential-stuffing campaign compromised roughly 1,800 accounts and drained stored balances via automated transfers.",
    affected_users: "1,800 confirmed compromised accounts",
    reported_harm: "Direct financial loss to affected users",
    urgency_level: "CRITICAL",
    decision_deadline: "Within 1 hour",
    current_response_hypothesis: "Freeze outbound transfers platform-wide and force re-authentication for all users",
    known_constraints: "Freezing transfers will also block legitimate transactions in progress",
    evidence_summary: "Fraud detection alerts and transaction pattern analysis showing rapid sequential transfers",
    evidence: [{ title: "Transaction pattern anomaly report", evidence_type: "FRAUD_ALERT", evidence_url: "https://en.wikipedia.org/wiki/Credential_stuffing", evidence_hash: "5c9e2b7a1f4d0836", source_name: "Fraud detection system", source_credibility_note: "Automated, corroborated by transfer logs", relevance: "Shows a common IP/device fingerprint pattern across compromised accounts", category: "TECHNICAL" }],
    response_options: [
      { title: "Platform-wide transfer freeze", summary: "Immediately halt all outbound transfers and require re-authentication.", action_type: "CONTAINMENT", expected_benefit: "Stops further fund loss across all accounts", key_risk: "Blocks legitimate in-flight transactions and angers unaffected users", affected_stakeholders: "All account holders", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "In-app banner and push notification", failure_conditions: "Freeze fails to stop transfers already queued" },
      { title: "Targeted freeze on flagged accounts only", summary: "Freeze only the accounts matching the compromise fingerprint.", action_type: "TARGETED_CONTAINMENT", expected_benefit: "Limits disruption to unaffected users", key_risk: "May miss accounts not yet flagged by the detection model", affected_stakeholders: "Flagged account holders", time_sensitivity: "IMMEDIATE", reversibility: "FULLY_REVERSIBLE", communication_requirement: "Direct notification to flagged users", failure_conditions: "New compromised accounts appear outside the flagged set" },
    ],
  },
  {
    tier: "IMMEDIATE_INTERVENTION",
    title: "Regulator flags undisclosed data-sharing practice",
    organisation: "Verdant Insurance Group",
    crisis_type: "REGULATORY_CRISIS",
    incident_summary: "A state regulator issued a formal inquiry into whether customer health data was shared with a marketing partner without proper disclosure.",
    affected_users: "Policyholders whose data may have been shared, estimated 90,000",
    reported_harm: "Potential privacy violation and regulatory penalty exposure",
    urgency_level: "HIGH",
    decision_deadline: "Within 5 business days",
    current_response_hypothesis: "Suspend the data-sharing arrangement and prepare a compliance response to the regulator",
    known_constraints: "Marketing partner contract has a 30-day termination notice clause",
    evidence_summary: "Copy of the regulator's inquiry letter and the data-sharing agreement",
    evidence: [{ title: "Regulator inquiry letter", evidence_type: "LEGAL_DOCUMENT", evidence_url: "https://en.wikipedia.org/wiki/Data_Protection_Directive", evidence_hash: "2e7b9c4f1a8d0356", source_name: "Legal department", source_credibility_note: "Official correspondence, verified authentic", relevance: "Specifies the exact disclosure requirement alleged to be unmet", category: "LEGAL" }],
    response_options: [
      { title: "Suspend data sharing and self-report", summary: "Pause the partner arrangement immediately and proactively respond to the regulator.", action_type: "COMPLIANCE_ACTION", expected_benefit: "Demonstrates good faith and may reduce penalty severity", key_risk: "Contractual penalty for early suspension", affected_stakeholders: "Policyholders, marketing partner, legal", time_sensitivity: "URGENT", reversibility: "REVERSIBLE", communication_requirement: "Formal regulator response, no public statement yet", failure_conditions: "Suspension breaches contract terms without a force majeure clause" },
      { title: "Continue sharing pending legal review", summary: "Maintain the current arrangement while legal reviews the disclosure requirements.", action_type: "MAINTAIN_STATUS_QUO", expected_benefit: "Avoids contractual penalties during review", key_risk: "Regulator may view continued sharing as an aggravating factor", affected_stakeholders: "Policyholders, legal", time_sensitivity: "STANDARD", reversibility: "REVERSIBLE", communication_requirement: "None externally", failure_conditions: "Regulator escalates to a formal enforcement action during review" },
    ],
  },

  // --- Tier: EMERGENCY_SHUTDOWN --------------------------------------------
  {
    tier: "EMERGENCY_SHUTDOWN",
    title: "Automated trading algorithm executing runaway erroneous trades",
    organisation: "Ashgrove Capital",
    crisis_type: "FINANCIAL_SYSTEM_MALFUNCTION",
    incident_summary: "A bug in the automated trading algorithm caused it to execute unintended large-volume trades for the past 20 minutes. The system is still active and continuing to trade uncontrolled, with losses mounting every minute.",
    affected_users: "All client accounts using the automated trading service, and the firm's own capital",
    reported_harm: "Ongoing uncontrolled financial losses, already substantial and increasing every minute the system remains active",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately — losses are accruing every second the system remains active",
    current_response_hypothesis: "Immediately trigger the full kill-switch for the automated trading system across all accounts",
    known_constraints: "A full shutdown will also halt legitimate in-flight trades for currently unaffected clients",
    evidence_summary: "Real-time trading system logs showing the erroneous trade pattern and mounting realized losses",
    evidence: [{ title: "Real-time trading system logs", evidence_type: "LOG", evidence_url: "https://en.wikipedia.org/wiki/Algorithmic_trading", evidence_hash: "4d5e6f7081922334", source_name: "Trading systems monitoring", source_credibility_note: "Automated, real-time, cross-checked against the clearing firm's trade confirmations", relevance: "Confirms the erroneous trade pattern is ongoing and quantifies the mounting realized losses", category: "TECHNICAL" }],
    response_options: [
      { title: "Emergency full shutdown of the trading system", summary: "Immediately kill-switch the entire automated trading system across all client accounts.", action_type: "EMERGENCY_SHUTDOWN", expected_benefit: "Stops the uncontrolled losses immediately across every account", key_risk: "Halts legitimate in-flight trades for clients unaffected by the bug", affected_stakeholders: "All clients using the automated trading service, the firm", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Immediate client notice and regulatory notification as required", failure_conditions: "Shutdown mechanism itself fails to halt the malfunctioning strategy" },
      { title: "Disable only the malfunctioning strategy module", summary: "Target only the specific strategy module believed to be causing the erroneous trades.", action_type: "TARGETED_SHUTDOWN", expected_benefit: "Preserves unrelated, unaffected trading strategies and client positions", key_risk: "If misdiagnosed, losses continue mounting while the wrong module is targeted", affected_stakeholders: "Clients using the malfunctioning strategy, the firm", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Immediate client notice for affected strategy users", failure_conditions: "The erroneous trading pattern continues after disabling the targeted module" },
    ],
  },
  {
    tier: "EMERGENCY_SHUTDOWN",
    title: "Reactor cooling system exhibiting anomalous pressure readings",
    organisation: "Ferrovia Energy",
    crisis_type: "OPERATIONAL_CRISIS",
    incident_summary: "The primary cooling system at a power generation facility is showing rapidly rising, anomalous pressure readings inconsistent with normal operating parameters, with the cause not yet identified.",
    affected_users: "Facility staff and the surrounding community within the emergency planning zone",
    reported_harm: "Imminent risk of equipment failure with potential for serious safety consequences if not halted",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Initiate an emergency shutdown of the affected system per established safety protocol",
    known_constraints: "An emergency shutdown will take the facility offline and affect regional power supply",
    evidence_summary: "Real-time pressure and temperature sensor readings from the cooling system",
    evidence: [{ title: "Cooling system sensor readings", evidence_type: "METRIC", evidence_url: "https://en.wikipedia.org/wiki/Nuclear_safety_and_security", evidence_hash: "6e7f809192a3b4c5", source_name: "Facility safety monitoring system", source_credibility_note: "Automated, real-time, redundant sensor confirmation", relevance: "Confirms the anomalous readings are real and rapidly escalating, not a sensor fault", category: "TECHNICAL" }],
    response_options: [
      { title: "Initiate emergency shutdown per safety protocol", summary: "Follow the established emergency shutdown procedure for the affected cooling system immediately.", action_type: "EMERGENCY_SHUTDOWN", expected_benefit: "Follows the proven safety protocol designed exactly for this scenario", key_risk: "Takes the facility offline, affecting regional power supply", affected_stakeholders: "Facility staff, surrounding community, regional power customers", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Immediate regulator and community notification per protocol", failure_conditions: "Shutdown protocol itself does not fully resolve the anomalous readings" },
      { title: "Reduce load and continue monitoring before full shutdown", summary: "Cut load significantly while continuing to monitor before committing to a full shutdown.", action_type: "PARTIAL_MITIGATION", expected_benefit: "Preserves partial power output if the anomaly stabilizes", key_risk: "Delays the proven safety response while risk continues to escalate", affected_stakeholders: "Facility staff, surrounding community", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal safety team alert", failure_conditions: "Readings continue to escalate despite the load reduction" },
    ],
  },
  {
    tier: "EMERGENCY_SHUTDOWN",
    title: "Fleet-wide critical mechanical defect discovered in aircraft component",
    organisation: "Halcyon Airlines",
    crisis_type: "SAFETY_INCIDENT",
    incident_summary: "A critical mechanical defect was discovered in a component shared across the entire aircraft fleet during a routine inspection, with the manufacturer confirming the defect could lead to component failure in flight.",
    affected_users: "All passengers on flights using aircraft with the affected component, and flight crews",
    reported_harm: "Risk of in-flight component failure with potential for a serious safety incident",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Ground the entire affected fleet immediately pending inspection and remediation",
    known_constraints: "Grounding the fleet will strand a significant number of passengers and cause major schedule disruption",
    evidence_summary: "Manufacturer's defect confirmation and the inspection report that discovered it",
    evidence: [{ title: "Manufacturer defect confirmation notice", evidence_type: "LEGAL_DOCUMENT", evidence_url: "https://en.wikipedia.org/wiki/Airworthiness_directive", evidence_hash: "7f8091a2b3c4d5e6", source_name: "Aircraft manufacturer", source_credibility_note: "Official manufacturer communication, highest credibility", relevance: "Confirms the defect and its potential in-flight failure consequences", category: "TECHNICAL" }],
    response_options: [
      { title: "Ground the entire affected fleet immediately", summary: "Halt all flights using aircraft with the affected component until inspected and remediated.", action_type: "EMERGENCY_SHUTDOWN", expected_benefit: "Eliminates the safety risk entirely and follows manufacturer guidance", key_risk: "Massive passenger disruption and significant financial cost", affected_stakeholders: "All passengers on affected flights, flight crews, ground operations", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Immediate passenger notification, regulator filing, public statement", failure_conditions: "Grounding cannot be executed before the next scheduled affected flight departs" },
      { title: "Inspect and clear aircraft individually before grounding all", summary: "Rapidly inspect each aircraft and only ground those that fail inspection.", action_type: "TARGETED_INSPECTION", expected_benefit: "Keeps unaffected aircraft flying, reducing disruption", key_risk: "Inspection may not reliably detect the defect before a failure occurs", affected_stakeholders: "Passengers on flights pending inspection, flight crews", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Passenger notification for delayed flights", failure_conditions: "The inspection method cannot reliably detect the defect" },
    ],
  },
  {
    tier: "EMERGENCY_SHUTDOWN",
    title: "Containment breach with imminent toxic gas release risk",
    organisation: "Cobalt Materials",
    crisis_type: "ENVIRONMENTAL_INCIDENT",
    incident_summary: "A containment vessel at a chemical processing plant is showing signs of structural failure, with plant engineers assessing an imminent risk of toxic gas release if not evacuated and shut down immediately.",
    affected_users: "Plant workers and residents in the surrounding area within the risk radius",
    reported_harm: "Imminent risk of toxic gas exposure if containment fails completely",
    urgency_level: "CRITICAL",
    decision_deadline: "Immediately",
    current_response_hypothesis: "Evacuate the plant, shut down the affected process, and notify emergency services and nearby residents",
    known_constraints: "Full plant shutdown will halt production for an extended, currently unknown period",
    evidence_summary: "Engineering assessment of the containment vessel's structural integrity",
    evidence: [{ title: "Containment vessel structural assessment", evidence_type: "AUDIT_REPORT", evidence_url: "https://en.wikipedia.org/wiki/Chemical_plant", evidence_hash: "8091a2b3c4d5e6f7", source_name: "Plant engineering team", source_credibility_note: "First-hand structural assessment by certified plant engineers", relevance: "Confirms the imminent structural failure risk and potential for gas release", category: "TECHNICAL" }],
    response_options: [
      { title: "Evacuate, shut down, and notify emergency services immediately", summary: "Execute full plant evacuation, emergency shutdown of the affected process, and notify authorities and nearby residents.", action_type: "EMERGENCY_SHUTDOWN", expected_benefit: "Maximizes safety for workers and the surrounding community", key_risk: "Extended production halt with unknown restart timeline", affected_stakeholders: "Plant workers, surrounding community, emergency services", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Immediate emergency services and community notification", failure_conditions: "Evacuation cannot be completed before a potential containment failure" },
      { title: "Attempt an emergency stabilization of the vessel first", summary: "Have engineers attempt to stabilize the containment vessel before committing to a full evacuation.", action_type: "ATTEMPT_STABILIZATION", expected_benefit: "Could avoid the disruption of a full evacuation and shutdown if successful", key_risk: "Delays evacuation while risk of a catastrophic release continues", affected_stakeholders: "Plant workers attempting stabilization, surrounding community", time_sensitivity: "IMMEDIATE", reversibility: "REVERSIBLE", communication_requirement: "Internal safety team alert only", failure_conditions: "Stabilization attempt fails and containment is breached before evacuation begins" },
    ],
  },
];
